'use strict';
const AudioMixer={context:null,chains:new Map(),master:null,
 filters(){const ctx=this.context,filters=[120,1000,8000].map(f=>{const n=ctx.createBiquadFilter();n.type='peaking';n.frequency.value=f;n.Q.value=Math.SQRT1_2;return n;});filters[0].connect(filters[1]);filters[1].connect(filters[2]);return filters;},
 async start(){if(!this.context){this.context=new AudioContext();this.master=this.filters();this.master[2].connect(this.context.destination);}await this.context.resume();this.update();},
 set(filters,eq={}){['low','mid','high'].forEach((k,i)=>filters[i].gain.setTargetAtTime(eq.enabled===false?0:eq[k]||0,this.context.currentTime,.015));},
 update(){if(!this.context)return;this.set(this.master,project.masterEq);for(const[id,chain]of this.chains)if(!renderer.sources.has(id)){chain.source.disconnect();chain.filters.forEach(f=>f.disconnect());this.chains.delete(id);}for(const c of project.clips){const media=renderer.sources.get(c.id);if(!media)continue;let chain=this.chains.get(c.id);if(!chain){const source=this.context.createMediaElementSource(media),filters=this.filters();source.connect(filters[0]);filters[2].connect(this.master[0]);chain={source,filters};this.chains.set(c.id,chain);}this.set(chain.filters,c.eq);}}
};
const audioToggle=togglePlay;togglePlay=function(){AudioMixer.start().catch(e=>toast(e.message));audioToggle();};
const audioFrame=renderFrame;renderFrame=function(){AudioMixer.update();audioFrame();};
const eqButton=actionButton('audioEQ','EQ','素材と全体の音質を編集',()=>{
 const selectedClip=selection(),clip=selectedClip?.kind==='media'&&assetFor(selectedClip)?.audio?selectedClip:null;
 const box=showDialog('オーディオ EQ','再生しながら音質を調整できます。120 Hz・1 kHz・8 kHz、各±18 dB。設定は保存と書き出しにも反映されます。');
 const scope=el('select');scope.setAttribute('aria-label','EQの適用先');scope.append(new Option('全体（マスター）','master'));if(clip){scope.append(new Option('選択素材：'+clipName(clip),'clip'));scope.value='clip';}box.append(scope);
 const sliders=el('div','eqbands'),target=()=>scope.value==='clip'?clip:project,field=()=>scope.value==='clip'?'eq':'masterEq';box.append(sliders);
 function draw(){sliders.replaceChildren();const eq=target()[field()]||{};for(const[band,name]of [['low','低域 · 120 Hz'],['mid','中域 · 1 kHz'],['high','高域 · 8 kHz']]){const row=el('label','eqband'),label=el('span','',name),input=el('input'),value=el('output','',(eq[band]||0)+' dB');input.type='range';input.min=-18;input.max=18;input.step=.5;input.value=eq[band]||0;input.setAttribute('aria-label',name);let editing=false;input.onpointerdown=input.onfocus=()=>editing=false;input.oninput=()=>{if(!editing){checkpoint();editing=true;}target()[field()]={...(target()[field()]||{}),[band]:+input.value,enabled:true};value.textContent=input.value+' dB';AudioMixer.update();scheduleSave();};row.append(label,input,value);sliders.append(row);}
 const bypass=el('input');bypass.type='checkbox';bypass.checked=eq.enabled!==false;const enabled=el('label','','EQを有効にする');enabled.prepend(bypass);bypass.onchange=()=>{checkpoint();target()[field()]={...eq,...target()[field()],enabled:bypass.checked};AudioMixer.update();scheduleSave();};sliders.append(enabled);}
 scope.onchange=draw;draw();const play=el('button','primary','再生 / 停止'),reset=el('button','wide','EQをリセット');play.onclick=()=>togglePlay();reset.onclick=()=>{checkpoint();target()[field()]={};AudioMixer.update();scheduleSave();draw();};box.append(play,reset);
});$('#help').before(eqButton);
const waveformCache=new Map(),waveformPending=new Set();
async function loadWaveform(asset){if(waveformPending.has(asset.id)||waveformCache.has(asset.id))return;waveformPending.add(asset.id);try{const r=await fetch('/api/waveform/'+asset.id);if(!r.ok)throw Error('waveform');const result=await r.json();if(result.pending){setTimeout(()=>{waveformPending.delete(asset.id);loadWaveform(asset);},2000);return;}waveformCache.set(asset.id,result);if(!dragging)renderTimeline();}catch{waveformCache.set(asset.id,{peaks:[]});}finally{waveformPending.delete(asset.id);}}
function paintWaveforms(){for(const node of document.querySelectorAll('.clip')){const clip=project.clips.find(c=>c.id===node.dataset.id),asset=clip&&assetFor(clip);if(!asset?.audio)continue;const data=waveformCache.get(asset.id);if(!data){loadWaveform(asset);continue;}if(!data.peaks?.length)continue;const canvas=document.createElement('canvas');canvas.width=Math.max(8,Math.min(1600,Math.round(clip.duration*zoom)));canvas.height=32;const ctx=canvas.getContext('2d');ctx.strokeStyle=asset.kind==='audio'?'#84dfe1':'#8caeaf';ctx.globalAlpha=.75;ctx.beginPath();for(let x=0;x<canvas.width;x++){const start=(clip.sourceIn+x/canvas.width*clip.duration)/asset.duration*data.peaks.length,end=(clip.sourceIn+(x+1)/canvas.width*clip.duration)/asset.duration*data.peaks.length;let peak=0;for(let i=Math.floor(start);i<=Math.min(data.peaks.length-1,Math.ceil(end));i++)peak=Math.max(peak,data.peaks[i]||0);ctx.moveTo(x,16-peak*15);ctx.lineTo(x,16+peak*15);}ctx.stroke();node.style.backgroundImage=`url(${canvas.toDataURL()})`;node.style.backgroundSize='100% 100%';node.classList.add('haswaveform');}}
const waveformTimeline=renderTimeline;renderTimeline=function(){waveformTimeline();paintWaveforms();};
