'use strict';
const translations={
 '⚙ 設定':'⚙ Settings','設定':'Settings','UIテーマ':'UI theme','UI言語':'UI language','ダーク':'Dark','ライト':'Light','設定を保存':'Save settings','サイズ・レイヤー数を変更':'Change size / layers','テーマと言語は次回起動時にも保持されます。':'Theme and language are remembered for the next session.',
 '◈　編集ワークスペース':'◈ Edit workspace','▧　プラグイン':'▧ Plugins','⌘ シェーダー':'⌘ Shaders','? 操作ガイド':'? Help','↗ 書き出し':'↗ Export','ローカル編集':'Local editor','新規':'New','開く':'Open','↓ 名前を付けて保存':'Save as','プロジェクト設定':'Project settings','新規プロジェクト':'New project','プロジェクト名':'Project name','サイズプリセット':'Size preset','フルHD':'Full HD','縦長':'Portrait','正方形':'Square','カスタム':'Custom','幅（px）':'Width (px)','高さ（px）':'Height (px)','レイヤー数（1〜128）':'Layers (1–128)','作成':'Create','変更を適用':'Apply changes',
 'メディアライブラリ':'Media library','＋ 素材を読み込む':'＋ Import media','標準素材':'Built-in assets','▰ 四角形':'▰ Rectangle','● 円':'● Circle','▲ 三角形':'▲ Triangle','★ 星':'★ Star','▣ 背景':'▣ Background','T テキスト':'T Text','◎ カメラ制御':'◎ Camera','◩ クリッピング':'◩ Clipping','楕円':'Ellipse','ひし形':'Diamond','六角形':'Hexagon','矢印':'Arrow','ハート':'Heart','リング':'Ring','直線':'Line','グリッド':'Grid','市松模様':'Checkerboard','グラデーション':'Gradient','タイムコード':'Timecode','字幕':'Subtitle','素材を検索':'Search media','⌕ 素材を検索':'⌕ Search media','プロジェクトの素材':'Project media','ローカル':'Local','動画・音声をここにドロップ':'Drop video or audio here','あなたのPCで処理':'Processed on your PC','素材を外部に送信しません':'Your media stays on this PC',
 'ビューポート':'Viewport','/ 3D 空間':'/ 3D space','/ 出力画面':'/ Output view','出力画面':'Output view','3D 空間':'3D space','空間編集':'Spatial editing','出力プレビュー':'Output preview','レイヤー優先':'Layer order','軽量プロキシ':'Lightweight proxy','オリジナル':'Original','再生画質':'Playback quality','編集視点を縮小':'Zoom out','編集視点を拡大':'Zoom in','視点をリセット':'Reset view','グリッドの表示':'Toggle grid','先頭へ':'Go to start','最後へ':'Go to end','再生 / 一時停止（Space）':'Play / pause (Space)',
 'インスペクター':'Inspector','素材を選択してください':'Select a clip','クリップ未選択':'No clip selected','素材の内容':'Content','中央に配置':'Center','前へ ↑':'Forward ↑','後ろへ ↓':'Backward ↓','位置・サイズ・アニメーション':'Transform / animation','タイミング・レイヤー・音量':'Timing / layer / volume','エフェクト・シェーダー':'Effects / shader','素材名':'Clip name','色':'Color','テキスト内容':'Text','文字サイズ':'Font size','文字揃え':'Alignment','左揃え':'Left','中央':'Center','右揃え':'Right','図形':'Shape','四角形':'Rectangle','円 / 楕円':'Circle / ellipse','三角形':'Triangle','星':'Star','幅':'Width','高さ':'Height','切り抜き対象':'Mask target','直下の表示素材（自動）':'Nearest lower clip (auto)','自動キー':'Auto key','◇ キー編集':'◇ Edit keys','位置 X':'Position X','位置 Y':'Position Y','奥行き Z':'Depth Z','スケール / ズーム':'Scale / zoom','回転':'Rotation','不透明度':'Opacity','配置時刻':'Start','素材の開始':'Source in','長さ':'Duration','レイヤー':'Layer','音量':'Volume','秒':'sec','エフェクトなし':'No color effect','カラー効果を解除':'Clear color effect','＋ プラグインを追加':'＋ Add effect','GLSL · 未適用':'GLSL · Not applied','⌘ シェーダーを編集':'⌘ Edit shader','シェーダーグラフ':'Shader graph',
 'レイヤー編集':'Layers','◇ キーフレーム':'◇ Keyframes','曲線編集':'Curve editor','＋ レイヤー':'＋ Layer','複製':'Duplicate','✂ 分割':'✂ Split','削除':'Delete','吸着 ON':'Snap ON','吸着 OFF':'Snap OFF','全体表示':'Fit timeline','再生位置':'Playhead','補間':'Interpolation','直線移動':'Linear','なめらか':'Smooth','瞬間移動':'Hold','ベジェ曲線':'Bezier','キーを削除':'Delete key','時間 / 秒':'Time / sec','上が前面':'Top is front','最前面':'Front','最背面':'Back','吸着':'Snap','タイムラインの高さ':'Timeline height','タイムラインの拡大率':'Timeline zoom','停止中':'Stopped','書き出し中':'Exporting','バックグラウンド処理なし':'No background jobs','ローカルエンジン接続済み':'Local engine connected','日本語 · ローカルワークスペース':'English · Local workspace','✓ 自動保存済み':'✓ Autosaved','✓ 復元しました':'✓ Restored','保存待ち…':'Saving…','未保存':'Not saved','保存に失敗':'Save failed',
 'エフェクトプラグイン':'Effect plugins','＋ 読み込む':'＋ Import','エフェクトを検索':'Search effects','エフェクトの分類':'Effect category','すべて':'All','カラー':'Color','色変換':'Color transform','映像効果':'Visual effects','アニメーション':'Animation','追加プラグイン':'Imported plugins','カラーを適用':'Apply color','シェーダーを適用':'Apply shader','夕暮れの温度':'Sunset tone','モノクローム':'Monochrome','ソフトフィルム':'Soft film','鮮やか':'Vivid','パステル':'Pastel','ノワール':'Noir','ローキー':'Low key','ハイキー':'High key','くすみカラー':'Muted','セピア':'Sepia','クールブルー':'Cool blue','アンバー':'Amber','ネガ反転':'Invert','ビネット':'Vignette','ポスタリゼーション':'Posterize','モザイク':'Pixelate','走査線':'Scanlines','波紋ウェーブ':'Wave','光のパルス':'Light pulse',
 'アニメーション曲線':'Animation curve','曲線のパラメーター':'Curve parameter','曲線の種類':'Curve type','ゆっくり開始':'Ease in','ゆっくり終了':'Ease out','ゆっくり開始・終了':'Ease in / out','自由なベジェ曲線':'Custom Bezier','開始・終了にキー':'Add start / end keys','現在位置にキー':'Key at playhead','選択キーを削除':'Delete selected key','キーフレーム曲線グラフ':'Keyframe curve graph','時刻（秒）':'Time (sec)','キーの時刻（秒）':'Key time (sec)','キーの値':'Key value','値':'Value','閉じる':'Close',
 '映像を書き出す':'Export video','解像度':'Resolution','カスタムサイズ':'Custom size','縦横比が異なる場合':'Aspect ratio handling','全体を収める（余白あり）':'Fit (letterbox)','画面を埋める（中央で切り抜き）':'Fill (center crop)','エンコーダー':'Encoder','自動（利用可能なGPUを優先）':'Auto (prefer available GPU)','画質・速度':'Quality / speed','標準':'Balanced','速度優先':'Faster','画質優先':'Higher quality','GPUの使用方針':'GPU policy','最大品質（GPU高負荷を許可）':'Maximum quality (allow high GPU load)','WebAssemblyで高速転送':'Fast WebAssembly transfer','MP4 書き出しを開始':'Start MP4 export','GPUを実際に試験しています…':'Testing GPU encoders…','映像を書き出しています':'Exporting video','準備中…':'Preparing…','書き出しを中止':'Cancel export','書き出しが完了しました':'Export complete','↓ MP4 をダウンロード':'↓ Download MP4',
 'オーディオ EQ':'Audio EQ','EQの適用先':'EQ target','全体（マスター）':'Master mix','低域 · 120 Hz':'Low · 120 Hz','中域 · 1 kHz':'Mid · 1 kHz','高域 · 8 kHz':'High · 8 kHz','EQを有効にする':'Enable EQ','再生 / 停止':'Play / stop','EQをリセット':'Reset EQ','追加するノード':'Node type','ノードを追加':'Add node','プレビュー':'Preview','素材に適用':'Apply to clip','GLSLを編集':'Edit GLSL','素材':'Source','色を乗せる':'Tint','反転':'Invert','白黒':'Grayscale','露出':'Exposure','階調':'Posterize','ミックス':'Mix','出力':'Output','出力 ●':'Output ●','● 入力':'● Input','接続とコンパイルを確認しました。':'Connections and compilation verified.',
 '素材の先頭へ':'Go to clip start','複製　Ctrl+D':'Duplicate  Ctrl+D','前のレイヤーへ':'Move to layer above','後ろのレイヤーへ':'Move to layer below','キーフレームを編集':'Edit keyframes','再生位置で分割　S':'Split at playhead  S','削除　Delete':'Delete',
 'カラー設定とGLSLシェーダーを各1つ併用できます。':'One color effect and one GLSL shader can be combined.',
 'カラーとシェーダーは各1つ併用できます。適用後はCtrl+Zで取り消せます。':'Combine one color effect and one shader. Undo with Ctrl+Z.',
 'タイムラインの素材をクリックすると、文字・色・大きさをここで調整できます。':'Select a timeline clip to edit text, color and size here.',
 '選択素材が表示時間の外にあります。先頭へ移動 →':'The selected clip is outside the playhead. Go to its start →',
 '左右にドラッグで時間移動 · 上下でレイヤー移動 · 右クリックで操作':'Drag horizontally to move in time, vertically to change layers. Right-click for actions.',
 '背景ドラッグで視点回転 · ホイールで拡大縮小 · Alt＋ドラッグで素材移動':'Drag the background to orbit · Scroll to zoom · Alt-drag to move a clip',
 '素材をドラッグで移動 · ホイールは編集表示の拡大縮小':'Drag to move a clip · Scroll to zoom the editor',
 '上のレイヤーが前面。':'Higher layers appear in front.','◇ を押すと現在時刻にキーを追加。':'Click ◇ to add a key at the playhead.',
 '素材を選択 → キーフレームタブでアニメーション編集':'Select a clip, then open Keyframes to animate.',
 '◆をドラッグで時刻変更 ／ 空白をダブルクリックで追加':'Drag ◆ to move a key / double-click an empty lane to add one.',
 '変更は自動保存されます。':'Changes are saved automatically.'
};
Object.assign(translations,{
 'キーボードショートカット':'Keyboard shortcuts','素材と全体の音質を編集':'Edit clip and master EQ','MP4 / MOV / WebM / WAV ほか':'MP4 / MOV / WebM / WAV and more','空間で、映像をつくる。':'Create video in space.','素材を読み込んで、最初のシーンを。':'Import media to build your first scene.','編集キャンバス':'Editing canvas','タイムライン編集モード':'Timeline editing mode','ドラッグで高さを変更 · ダブルクリックで標準に戻す':'Drag to resize / double-click to reset','スケール・位置などの変化をグラフで編集':'Edit scale and position as animation curves','元に戻す（Ctrl+Z）':'Undo (Ctrl+Z)','やり直す（Ctrl+Shift+Z）':'Redo (Ctrl+Shift+Z)','素材を複製（Ctrl+D）':'Duplicate clip (Ctrl+D)','再生位置で分割（S）':'Split at playhead (S)','選択を削除（Delete）':'Delete selection (Delete)','素材の端・再生位置に吸着（Altで一時解除）':'Snap to clip edges and playhead (hold Alt to bypass)','映像全体を画面に収める（F）':'Fit the entire timeline (F)',
 'サイズを変更しても素材の位置や大きさの数値は維持します。編集画面と書き出しの基準サイズを設定します。':'Set the project canvas size. Existing position and scale values are preserved.',
 '30 fps · 幅・高さは偶数、総画素数は4K UHD以下。レイヤー数を減らす場合は空のレイヤーのみ削除できます。':'30 fps. Dimensions must be even; total pixels must not exceed 4K UHD. Only empty layers can be removed.',
 '暖色と柔らかなコントラスト':'A vibrant tone with soft contrast','光と陰影を際立たせる':'Emphasize light and shadow','落ち着いたフィルム調':'A restrained film-like tone',
 '彩度とコントラストを上げ、色をくっきり見せます。':'Increase saturation and contrast for vivid color.','淡い色と柔らかい陰影。背景や日常映像に。':'Pale colors and soft shadows for everyday footage.','強いコントラストの白黒表現。':'High-contrast black and white.','明るさを抑えて、落ち着いた雰囲気に。':'Lower brightness for a subdued mood.','明るく軽やかなトーンに整えます。':'Bright and airy tones.','彩度を抑えた控えめな色調。':'Soft, desaturated colors.','古い写真のような茶色の色調。':'Warm brown tones like an old photograph.','青みを加えて、冷たい空気感を表現。':'Add blue tones for a cool atmosphere.','赤と黄を強め、暖かな光を表現。':'Boost reds and yellows for warmer light.','RGBを反転してネガフィルム風に。':'Invert RGB channels for a negative-film effect.','画面の周囲を暗くし、中央を強調。':'Darken the edges to emphasize the center.','色を6段階に分け、イラストのように。':'Reduce color to six levels for a graphic look.','画面を80列のブロックに分割します。':'Divide the image into 80 columns of blocks.','横方向のラインでレトロモニター風に。':'Horizontal lines for a retro monitor look.','時間とともに映像が横へ揺れる効果。':'Animate the image with a horizontal wave.','2秒周期でゆっくり明るさを変化。':'Pulse brightness on a two-second cycle.',
 '再生しながら音質を調整できます。120 Hz・1 kHz・8 kHz、各±18 dB。設定は保存と書き出しにも反映されます。':'Adjust the sound during playback: 120 Hz, 1 kHz and 8 kHz, each ±18 dB. Settings are saved and applied to exports.',
 '出力端子をクリックしてから入力端子をクリックすると接続します。ノード上部をドラッグして配置。適用するまでは素材を変更しません。':'Click an output socket, then an input socket to connect. Drag node headers to arrange them. Apply to commit your graph.',
 '横軸は素材内の時間、縦軸は値。●を動かしてキーを編集し、選択キーから次のキーまでの曲線をハンドルで調整します。':'Horizontal: local clip time. Vertical: value. Drag key points and handles to shape the segment leading to the next key.',
 'GPUは映像圧縮に使用します。描画・素材のシークは別処理です。WASMが利用できない場合はPNG転送に切り替えます。':'GPU is used for video encoding. Rendering and seeking are separate. PNG transfer is used when WASM is unavailable.',
 '最大品質はGPUの解析・圧縮を強化します。GPU使用率100%を保証するものではありません。CPUは選択できません。':'Maximum quality enables heavier GPU analysis and encoding. It does not guarantee 100% utilization and requires a GPU encoder.',
 'プロジェクトと異なる縦横比では上記の設定を適用します。幅・高さは128〜4096の偶数、総画素数は4K UHD以下。':'Choose how to handle a different aspect ratio. Dimensions: even integers from 128 to 4096; total pixels up to 4K UHD.'
});
const originalTexts=new WeakMap(),originalAttrs=new WeakMap();
Object.assign(translations,{'クリップ未選択':'No clip selected','クリックしてタイムラインに追加':'Click to add to timeline','XとYを中央に配置':'Center X and Y','1つ上のレイヤーへ':'Move to layer above','1つ下のレイヤーへ':'Move to layer below','共通レンダラーでアニメーション・文字・クリッピング・シェーダーを元画質から描画します。このタブを開いたままお待ちください。':'Rendering animation, text, clipping and shaders from original media. Keep this tab open.'});
function translateText(text){if(preferences.language!=='en')return text;const trim=text.trim();if(translations[trim])return text.replace(trim,translations[trim]);return text.replace('4K UHD · 3840 × 2160','4K UHD · 3840 × 2160').replace('フルHD ·','Full HD ·').replace('縦長 ·','Portrait ·').replace('正方形 ·','Square ·').replace('選択素材：','Selected clip: ').replace(' · 最背面',' · Back').replace(' · 使用不可',' · Unavailable');}
window.translateUI=function(){const walker=document.createTreeWalker(document.body,NodeFilter.SHOW_TEXT);let n;while(n=walker.nextNode()){if(n.parentElement?.id==='selectionName'&&n.textContent==='クリップ未選択')n.textContent=translateText(n.textContent);if(n.parentElement?.closest('script,style,textarea,#projectName,.cliptitle,#selectionName,.assettext'))continue;let record=originalTexts.get(n);if(!record||n.textContent!==record.last)record={original:n.textContent,last:n.textContent};const value=translateText(record.original);if(n.textContent!==value)n.textContent=value;record.last=value;originalTexts.set(n,record);}for(const node of document.querySelectorAll('[title],[aria-label],[placeholder]')){let records=originalAttrs.get(node)||{};for(const key of ['title','aria-label','placeholder']){if(!node.hasAttribute(key))continue;let r=records[key];if(!r||node.getAttribute(key)!==r.last)r={original:node.getAttribute(key)};const value=translateText(r.original);if(node.getAttribute(key)!==value)node.setAttribute(key,value);r.last=value;records[key]=r;}originalAttrs.set(node,records);}};
let translateQueued=false;new MutationObserver(()=>{if(translateQueued)return;translateQueued=true;queueMicrotask(()=>{translateQueued=false;window.translateUI();});}).observe(document.body,{subtree:true,childList:true,characterData:true,attributes:true,attributeFilter:['title','aria-label','placeholder']});
window.translateUI();

window.uiText=translateText;
