const params=new URLSearchParams(location.search),kind=params.get('panel'),channel=new BroadcastChannel('lattice-panels-'+params.get('session')),root=document.querySelector('#remote');let selection=null,pending=null,lastSeen=Date.now();
function render(m){if(selection===m.selection&&root.contains(document.activeElement)&&document.activeElement.matches('input,textarea,select')){pending=m;return;}selection=m.selection;root.innerHTML=m.html;document.documentElement.dataset.theme=m.theme;pending=null;}
channel.onmessage=({data:m})=>{if(m.type==='shutdown'||m.kind===kind&&m.type==='close'){if(window.pywebview?.api?.close_panel)window.pywebview.api.close_panel(params.get('session'),kind);else window.close();root.replaceChildren();document.querySelector('#status').textContent='メインに戻しました';return;}if(m.kind!==kind||m.type!=='render')return;lastSeen=Date.now();document.querySelector('#status').textContent='メインと同期中';render(m);};
channel.postMessage({type:'hello',kind});setInterval(()=>{channel.postMessage({type:'heartbeat',kind});if(Date.now()-lastSeen>10000)channel.postMessage({type:'hello',kind});},1500);
document.querySelector('#dock').onclick=()=>channel.postMessage({type:'dock',kind});
for(const event of ['click','input','change'])root.addEventListener(event,e=>{const target=e.target.closest('[data-remote-id]');if(!target)return;if(event==='click'&&['import','installPlugin'].includes(target.id)){remoteImport(target.id==='installPlugin');return;}if(event==='click'&&target.matches('input,select,textarea'))return;channel.postMessage({type:'action',kind,id:target.dataset.remoteId,event,selection,value:target.value,checked:target.checked});});
root.addEventListener('focusout',()=>setTimeout(()=>{if(pending)render(pending);},0));window.addEventListener('beforeunload',()=>channel.postMessage({type:'dock',kind}));

async function remoteImport(plugin){const picker=document.createElement('input');picker.type='file';picker.accept=plugin?'.json':'video/*,audio/*,.mkv,.mov';picker.multiple=!plugin;picker.onchange=async()=>{try{document.querySelector('#status').textContent='読み込み中…';const state=await(await fetch('/api/state')).json();for(const file of picker.files){const response=await fetch(plugin?'/api/plugin':'/api/import',{method:'POST',headers:{'X-Lattice-Token':state.token,...(plugin?{'Content-Type':'application/json'}:{'X-Filename':encodeURIComponent(file.name)})},body:plugin?await file.text():file});const data=await response.json();if(!response.ok)throw Error(data.error||'読み込みに失敗しました');}document.querySelector('#status').textContent='読み込みました';}catch(e){document.querySelector('#status').textContent=e.message;}};picker.click();}
