'use strict';
function shaderGraphDialog(){
 const clip=selection();if(!clip||['camera','mask'].includes(clip.kind)||exporting)return toast('映像・図形・テキストを選択してください。');
 stop();setWorkspaceTab('shader');const box=showDialog('シェーダーグラフ','出力端子をクリックしてから入力端子をクリックすると接続します。ノード上部をドラッグして配置。適用するまでは素材を変更しません。');$('#dialog').classList.add('graphdialog');
 let graph=C.clone(clip.shader?.graph||ShaderGraph.initial()),pending=null;
 if(!Array.isArray(graph.nodes)||!Array.isArray(graph.links))graph=ShaderGraph.initial();
 const bar=el('div','graphbar'),type=el('select');type.setAttribute('aria-label','追加するノード');for(const[k,v]of Object.entries(ShaderGraph.types))if(k!=='output')type.append(new Option(v,k));const add=el('button','','ノードを追加'),test=el('button','','プレビュー'),apply=el('button','primary','素材に適用'),source=el('button','','GLSLを編集');bar.append(type,add,test,apply,source);box.append(bar);
 const surface=el('div','graphsurface'),svg=document.createElementNS('http://www.w3.org/2000/svg','svg'),board=el('div','graphboard');svg.setAttribute('class','graphlinks');board.append(svg);surface.append(board);box.append(surface);
 const status=el('p','graphstatus',''),preview=document.createElement('canvas');preview.width=480;preview.height=270;preview.className='graphpreview';box.append(preview,status);
 function paths(){svg.replaceChildren();for(const link of graph.links){const a=graph.nodes.find(n=>n.id===link.from),b=graph.nodes.find(n=>n.id===link.to);if(!a||!b)continue;const x1=a.x+176,y1=a.y+62,x2=b.x,y2=b.y+62+link.slot*28,p=document.createElementNS(svg.namespaceURI,'path');p.setAttribute('d',`M${x1},${y1} C${x1+70},${y1} ${x2-70},${y2} ${x2},${y2}`);p.setAttribute('stroke','#b4d9f7');p.setAttribute('fill','none');p.setAttribute('stroke-width','3');svg.append(p);}}
 function draw(){for(const n of [...board.querySelectorAll('.graphnode')])n.remove();for(const n of graph.nodes){const card=el('div','graphnode');card.style.left=n.x+'px';card.style.top=n.y+'px';const head=el('div','graphhead',ShaderGraph.types[n.type]);card.append(head);head.onpointerdown=e=>{if(e.button!==0)return;const x=e.clientX,y=e.clientY,ox=n.x,oy=n.y;beginDrag(e,head,p=>{n.x=C.clamp(ox+p.clientX-x,0,1020);n.y=C.clamp(oy+p.clientY-y,0,480);card.style.left=n.x+'px';card.style.top=n.y+'px';paths();});};
  if(n.type!=='source')for(let slot=0;slot<(n.type==='mix'?2:1);slot++){const input=el('button','graphport input','● '+(slot?'B':'入力'));input.style.top=(51+slot*28)+'px';input.title='接続先 / 右クリックで解除';input.onclick=()=>{if(!pending)return;graph.links=graph.links.filter(l=>!(l.to===n.id&&l.slot===slot));graph.links.push({from:pending,to:n.id,slot});pending=null;draw();compilePreview();};input.oncontextmenu=e=>{e.preventDefault();graph.links=graph.links.filter(l=>!(l.to===n.id&&l.slot===slot));draw();};card.append(input);}
  if(n.type!=='output'){const output=el('button','graphport output','出力 ●');output.style.top='51px';output.onclick=()=>{pending=n.id;status.textContent='接続する入力端子を選択してください。';};card.append(output);}
  if(n.type==='tint'){const color=el('input');color.type='color';color.value=n.color||'#ffffff';color.setAttribute('aria-label','ノードの色');color.oninput=()=>{n.color=color.value;compilePreview();};card.append(color);}
  if(['exposure','mix','poster'].includes(n.type)){const value=el('input');value.type='number';value.step=n.type==='poster'?1:.1;value.min=n.type==='exposure'?-4:n.type==='mix'?0:2;value.max=n.type==='exposure'?4:n.type==='mix'?1:32;value.value=n.value??(n.type==='mix'?.5:n.type==='poster'?6:0);value.setAttribute('aria-label',ShaderGraph.types[n.type]+'の値');value.oninput=()=>{n.value=+value.value;compilePreview();};card.append(value);}
  if(n.type!=='output'){const remove=el('button','graphdelete','×');remove.title='ノードを削除';remove.onclick=()=>{graph.nodes=graph.nodes.filter(v=>v!==n);graph.links=graph.links.filter(l=>l.to!==n.id&&l.from!==n.id);draw();};card.append(remove);}board.append(card);
 }paths();}
 function compilePreview(){try{const code=ShaderGraph.compile(graph);renderer.shader.compile(code);const snapshot=C.clone(project),c=snapshot.clips.find(c=>c.id===clip.id);c.shader={enabled:true,code};const oldCanvas=renderer.canvas,oldCtx=renderer.ctx;try{renderer.canvas=preview;renderer.ctx=preview.getContext('2d');renderer.draw(snapshot,C.clamp(time,clip.start,clip.start+clip.duration-1/30),{strict:true});}finally{renderer.canvas=oldCanvas;renderer.ctx=oldCtx;renderFrame();}status.textContent='接続とコンパイルを確認しました。';status.classList.remove('error');return code;}catch(e){status.textContent=e.message;status.classList.add('error');return null;}}
 add.onclick=()=>{if(graph.nodes.length>=32)return toast('ノードは32個までです。');graph.nodes.push({id:crypto.randomUUID(),type:type.value,x:220+Math.random()*180,y:40+Math.random()*220,color:'#ffffff'});draw();};test.onclick=compilePreview;apply.onclick=()=>{const code=compilePreview();if(!code)return;checkpoint();clip.shader={enabled:true,code,graph:C.clone(graph),name:'シェーダーグラフ'};changed();$('#dialog').close();toast('シェーダーグラフを適用しました。');};source.onclick=()=>{shaderDialog();setWorkspaceTab('shader');};draw();compilePreview();
}
